version: "3.8"

services:
  nuxt-app:
    image: node:20-alpine
    container_name: nuxt_app_dev
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
    command: sh -c "yarn install && yarn run dev -- --host 0.0.0.0"
    restart: unless-stopped
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge